import { imagens } from "./images";
import { criarSecoes, horariosPadrao, metricasPadrao } from "./factory";
import type { Site } from "./types";

const base = (over: Partial<Site> & Pick<Site, "id" | "slug" | "modeloId">): Site => {
  const agora = new Date();
  return {
    status: "publicado",
    criadoEm: new Date(agora.getTime() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    atualizadoEm: new Date(agora.getTime() - 1000 * 60 * 60 * 6).toISOString(),
    cliente: {
      empresa: "Empresa",
      segmento: "servicos",
      responsavel: "Responsável",
      telefone: "(11) 98888-1111",
      email: "contato@empresa.com.br",
      cidade: "São Paulo",
      estado: "SP",
    },
    conteudo: {
      nome: "Empresa",
      descricao: "",
      telefone: "(11) 98888-1111",
      whatsapp: "11988881111",
      email: "contato@empresa.com.br",
      instagram: "",
      endereco: "São Paulo - SP",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#b8ff3c",
      corFundo: "#111111",
      corTexto: "#ffffff",
      fonte: "moderna",
      raio: 16,
      botao: "solido",
      tema: "escuro",
      animacoes: true,
      espacamento: "confortavel",
      layout: "cards",
      capaTipo: "imagem",
    },
    secoes: criarSecoes(),
    links: [],
    produtos: [],
    servicos: [],
    galeria: [],
    depoimentos: [],
    equipe: [],
    cupons: [],
    faq: [],
    formulario: {
      tipo: "orcamento",
      titulo: "Solicite um orçamento",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Mensagem", tipo: "textarea", obrigatorio: false },
      ],
    },
    seo: { titulo: "", descricao: "", palavras: "" },
    integracoes: {
      googleAnalytics: "",
      metaPixel: "",
      dominio: "",
      googleMaps: "",
      whatsappApi: "",
    },
    metricas: metricasPadrao(90),
    ...over,
  } as Site;
};

const ligarSecoes = (site: Site, ativas: string[]) => {
  site.secoes = site.secoes.map((s) => ({ ...s, ativa: ativas.includes(s.tipo) }));
  return site;
};

export function sitesDemo(): Site[] {
  const cantina = base({
    id: "site_cantina",
    slug: "cantina-do-vale",
    modeloId: "restaurante-moderno",
    cliente: {
      empresa: "Cantina do Vale",
      segmento: "alimentacao",
      responsavel: "Marina Bertoldi",
      telefone: "(11) 97412-3388",
      email: "contato@cantinadovale.com.br",
      cidade: "Campinas",
      estado: "SP",
    },
    conteudo: {
      nome: "Cantina do Vale",
      descricao:
        "Massas artesanais, forno a lenha e um cantinho italiano no coração de Campinas. Peça pelo WhatsApp ou reserve sua mesa.",
      capa: imagens.restaurante,
      telefone: "(19) 3234-5566",
      whatsapp: "5519974123388",
      email: "contato@cantinadovale.com.br",
      instagram: "cantinadovale",
      endereco: "Rua das Oliveiras, 340 - Cambuí, Campinas - SP",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#e2b04a",
      corFundo: "#12100e",
      corTexto: "#f7f3ec",
      fonte: "editorial",
      raio: 14,
      botao: "solido",
      tema: "escuro",
      animacoes: true,
      espacamento: "amplo",
      layout: "editorial",
      capaTipo: "imagem",
    },
    produtos: [
      {
        id: "p1",
        nome: "Rondelli de funghi",
        descricao: "Massa fresca recheada com funghi secchi e creme de parmesão.",
        preco: 68.9,
        categoria: "Massas",
        variacoes: ["Individual", "Para dois"],
        imagem: imagens.restaurante,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Pizza margherita napoletana",
        descricao: "Fermentação de 48h, tomate San Marzano e manjericão fresco.",
        preco: 59,
        precoPromocional: 49.9,
        categoria: "Pizzas",
        variacoes: ["Média", "Grande"],
        imagem: imagens.hamburgueria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Tiramisù da casa",
        descricao: "Receita da nonna, com café coado na hora.",
        preco: 27,
        categoria: "Sobremesas",
        variacoes: [],
        disponivel: true,
        destaque: false,
      },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Rafael Amorim",
        nota: 5,
        comentario: "Melhor massa da região. Atendimento impecável e entrega rápida.",
        data: "2026-06-12",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Juliana Prado",
        nota: 5,
        comentario: "Reservei pelo site em 30 segundos. Ambiente lindo.",
        data: "2026-05-28",
        destaque: false,
      },
    ],
    galeria: [
      { id: "g1", url: imagens.restaurante, titulo: "Salão" },
      { id: "g2", url: imagens.hamburgueria, titulo: "Forno" },
    ],
    cupons: [
      {
        id: "cp1",
        titulo: "10% na primeira visita",
        descricao: "Válido para pedidos acima de R$ 80 pelo WhatsApp.",
        codigo: "VALE10",
        validade: "2026-12-31",
        ativo: true,
      },
    ],
    faq: [
      {
        id: "f1",
        pergunta: "Vocês entregam?",
        resposta: "Sim, em toda a região do Cambuí e Nova Campinas.",
      },
      {
        id: "f2",
        pergunta: "Aceitam reserva?",
        resposta: "Sim, pelo WhatsApp com até 2 dias de antecedência.",
      },
    ],
    links: [
      { id: "l1", tipo: "whatsapp", titulo: "Fazer pedido", valor: "5519974123388", ativo: true },
      {
        id: "l2",
        tipo: "instagram",
        titulo: "@cantinadovale",
        valor: "cantinadovale",
        ativo: true,
      },
      {
        id: "l3",
        tipo: "localizacao",
        titulo: "Como chegar",
        valor: "Rua das Oliveiras, 340",
        ativo: true,
      },
    ],
  });
  ligarSecoes(cantina, [
    "apresentacao",
    "cardapio",
    "produtos",
    "galeria",
    "depoimentos",
    "cupom",
    "localizacao",
    "horarios",
    "faq",
    "rodape",
  ]);

  const navalha = base({
    id: "site_navalha",
    slug: "navalha-de-ouro",
    modeloId: "barbearia-premium",
    cliente: {
      empresa: "Navalha de Ouro",
      segmento: "beleza",
      responsavel: "Diego Menezes",
      telefone: "(21) 98812-4477",
      email: "contato@navalhadeouro.com.br",
      cidade: "Niterói",
      estado: "RJ",
    },
    conteudo: {
      nome: "Navalha de Ouro",
      descricao:
        "Barbearia clássica com atendimento por hora marcada. Corte, barba e cuidado de verdade.",
      capa: imagens.barbearia,
      telefone: "(21) 3622-9090",
      whatsapp: "5521988124477",
      email: "contato@navalhadeouro.com.br",
      instagram: "navalhadeouro",
      endereco: "Av. Amaral Peixoto, 120 - Centro, Niterói - RJ",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#c9a227",
      corFundo: "#141414",
      corTexto: "#f5f1e8",
      fonte: "elegante",
      raio: 8,
      botao: "contorno",
      tema: "escuro",
      animacoes: true,
      espacamento: "confortavel",
      layout: "imersivo",
      capaTipo: "imagem",
    },
    servicos: [
      {
        id: "s1",
        nome: "Corte social",
        descricao: "Máquina, tesoura e finalização.",
        duracao: "45 min",
        preco: 70,
        profissional: "Diego",
      },
      {
        id: "s2",
        nome: "Barba terapia",
        descricao: "Toalha quente, óleo e navalha.",
        duracao: "40 min",
        preco: 60,
        profissional: "Ricardo",
      },
      {
        id: "s3",
        nome: "Combo completo",
        descricao: "Corte + barba + sobrancelha.",
        duracao: "1h20",
        preco: 120,
        profissional: "Diego",
      },
    ],
    equipe: [
      { id: "e1", nome: "Diego Menezes", funcao: "Barbeiro-chefe" },
      { id: "e2", nome: "Ricardo Alves", funcao: "Barbeiro" },
    ],
    galeria: [{ id: "g1", url: imagens.barbearia, titulo: "Ambiente" }],
    depoimentos: [
      {
        id: "d1",
        nome: "Thiago Souza",
        nota: 5,
        comentario: "Agendamento fácil e corte perfeito.",
        data: "2026-07-02",
        destaque: true,
      },
    ],
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: "Agendar horário",
        valor: "5521988124477",
        ativo: true,
      },
      {
        id: "l2",
        tipo: "instagram",
        titulo: "Portfólio no Instagram",
        valor: "navalhadeouro",
        ativo: true,
      },
    ],
  });
  ligarSecoes(navalha, [
    "apresentacao",
    "servicos",
    "equipe",
    "galeria",
    "depoimentos",
    "localizacao",
    "horarios",
    "rodape",
  ]);

  const ateliê = base({
    id: "site_atelie",
    slug: "atelie-lume",
    modeloId: "loja-roupas",
    status: "rascunho",
    cliente: {
      empresa: "Ateliê Lume",
      segmento: "comercio",
      responsavel: "Camila Ferraz",
      telefone: "(31) 99654-2210",
      email: "oi@atelielume.com.br",
      cidade: "Belo Horizonte",
      estado: "MG",
    },
    conteudo: {
      nome: "Ateliê Lume",
      descricao: "Roupas de alfaiataria leve, produzidas em pequenos lotes em Belo Horizonte.",
      capa: imagens.moda,
      telefone: "(31) 99654-2210",
      whatsapp: "5531996542210",
      email: "oi@atelielume.com.br",
      instagram: "atelie.lume",
      endereco: "Rua Fernandes Tourinho, 88 - Savassi, Belo Horizonte - MG",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#c1633f",
      corFundo: "#faf6f1",
      corTexto: "#201c18",
      fonte: "moderna",
      raio: 4,
      botao: "contorno",
      tema: "claro",
      animacoes: true,
      espacamento: "amplo",
      layout: "catalogo",
      capaTipo: "imagem",
    },
    produtos: [
      {
        id: "p1",
        nome: "Blazer linho areia",
        descricao: "Linho puro, forro em algodão.",
        preco: 489,
        categoria: "Alfaiataria",
        variacoes: ["P", "M", "G"],
        imagem: imagens.moda,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Calça pantalona",
        descricao: "Caimento fluido, cintura alta.",
        preco: 329,
        precoPromocional: 279,
        categoria: "Alfaiataria",
        variacoes: ["36", "38", "40", "42"],
        imagem: imagens.moda,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Camisa seda off",
        descricao: "Toque frio, botões de madrepérola.",
        preco: 359,
        categoria: "Camisaria",
        variacoes: ["P", "M", "G"],
        disponivel: false,
        destaque: false,
      },
    ],
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: "Comprar pelo WhatsApp",
        valor: "5531996542210",
        ativo: true,
      },
      { id: "l2", tipo: "instagram", titulo: "@atelie.lume", valor: "atelie.lume", ativo: true },
    ],
  });
  ligarSecoes(ateliê, ["apresentacao", "produtos", "promocao", "galeria", "localizacao", "rodape"]);

  const rota = base({
    id: "site_rota",
    slug: "rota-norte-transportes",
    modeloId: "transportadora",
    cliente: {
      empresa: "Rota Norte Transportes",
      segmento: "transporte",
      responsavel: "Anderson Lima",
      telefone: "(41) 99120-7788",
      email: "comercial@rotanorte.com.br",
      cidade: "Curitiba",
      estado: "PR",
    },
    conteudo: {
      nome: "Rota Norte Transportes",
      descricao:
        "Cargas fracionadas e dedicadas para todo o Sul e Sudeste. Cotação em até 2 horas.",
      capa: imagens.transporte,
      telefone: "(41) 3355-1200",
      whatsapp: "5541991207788",
      email: "comercial@rotanorte.com.br",
      instagram: "rotanortetransportes",
      endereco: "BR-116, km 92 - Curitiba - PR",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#ff9f1c",
      corFundo: "#0f1620",
      corTexto: "#eef4fb",
      fonte: "tecnica",
      raio: 10,
      botao: "solido",
      tema: "escuro",
      animacoes: true,
      espacamento: "confortavel",
      layout: "corporativo",
      capaTipo: "imagem",
    },
    servicos: [
      {
        id: "s1",
        nome: "Carga fracionada",
        descricao: "Coletas diárias na região metropolitana.",
        duracao: "24-72h",
        preco: 0,
      },
      {
        id: "s2",
        nome: "Carga dedicada",
        descricao: "Veículo exclusivo com rastreamento.",
        duracao: "Sob demanda",
        preco: 0,
      },
    ],
    formulario: {
      tipo: "cotacao",
      titulo: "Solicitar cotação de frete",
      campos: [
        { id: "c1", rotulo: "Empresa", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "Origem", tipo: "texto", obrigatorio: true },
        { id: "c3", rotulo: "Destino", tipo: "texto", obrigatorio: true },
        { id: "c4", rotulo: "Detalhes da carga", tipo: "textarea", obrigatorio: false },
      ],
    },
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: "Falar com o comercial",
        valor: "5541991207788",
        ativo: true,
      },
    ],
  });
  ligarSecoes(rota, ["apresentacao", "servicos", "formulario", "faq", "localizacao", "rodape"]);

  const studio = base({
    id: "site_studio",
    slug: "studio-clara-luz",
    modeloId: "fotografo",
    status: "pausado",
    cliente: {
      empresa: "Studio Clara Luz",
      segmento: "profissionais",
      responsavel: "Clara Nogueira",
      telefone: "(51) 98330-4412",
      email: "clara@claraluz.foto",
      cidade: "Porto Alegre",
      estado: "RS",
    },
    conteudo: {
      nome: "Studio Clara Luz",
      descricao: "Ensaios editoriais, casamentos e fotografia de marca com luz natural.",
      capa: imagens.fotografo,
      telefone: "(51) 98330-4412",
      whatsapp: "5551983304412",
      email: "clara@claraluz.foto",
      instagram: "studioclaraluz",
      endereco: "Rua Padre Chagas, 210 - Moinhos de Vento, Porto Alegre - RS",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#e8e2d4",
      corFundo: "#101010",
      corTexto: "#f0eeea",
      fonte: "elegante",
      raio: 2,
      botao: "contorno",
      tema: "escuro",
      animacoes: true,
      espacamento: "amplo",
      layout: "minimalista",
      capaTipo: "imagem",
    },
    galeria: [
      { id: "g1", url: imagens.fotografo, titulo: "Estúdio" },
      { id: "g2", url: imagens.moda, titulo: "Editorial" },
      { id: "g3", url: imagens.salao, titulo: "Beleza" },
    ],
    servicos: [
      {
        id: "s1",
        nome: "Ensaio editorial",
        descricao: "2h de sessão, 30 fotos tratadas.",
        duracao: "2h",
        preco: 1200,
      },
      {
        id: "s2",
        nome: "Fotografia de marca",
        descricao: "Banco de imagens para redes sociais.",
        duracao: "4h",
        preco: 2400,
      },
    ],
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: "Pedir orçamento",
        valor: "5551983304412",
        ativo: true,
      },
    ],
  });
  ligarSecoes(studio, ["apresentacao", "galeria", "servicos", "formulario", "rodape"]);

  const vitalis = base({
    id: "site_vitalis",
    slug: "clinica-vitalis",
    modeloId: "clinica",
    cliente: {
      empresa: "Clínica Vitalis",
      segmento: "saude",
      responsavel: "Dra. Helena Braga",
      telefone: "(62) 98277-1190",
      email: "atendimento@clinicavitalis.com.br",
      cidade: "Goiânia",
      estado: "GO",
    },
    conteudo: {
      nome: "Clínica Vitalis",
      descricao: "Consultas, exames e acompanhamento multidisciplinar em um só lugar.",
      capa: imagens.clinica,
      telefone: "(62) 3241-8080",
      whatsapp: "5562982771190",
      email: "atendimento@clinicavitalis.com.br",
      instagram: "clinicavitalis",
      endereco: "Av. T-9, 1500 - Setor Bueno, Goiânia - GO",
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: "#1f7a8c",
      corFundo: "#f6f9fb",
      corTexto: "#132029",
      fonte: "moderna",
      raio: 18,
      botao: "suave",
      tema: "claro",
      animacoes: true,
      espacamento: "confortavel",
      layout: "corporativo",
      capaTipo: "imagem",
    },
    servicos: [
      {
        id: "s1",
        nome: "Clínica geral",
        descricao: "Consulta de rotina e encaminhamentos.",
        duracao: "40 min",
        preco: 280,
      },
      {
        id: "s2",
        nome: "Nutrição",
        descricao: "Plano alimentar individualizado.",
        duracao: "50 min",
        preco: 240,
      },
      {
        id: "s3",
        nome: "Cardiologia",
        descricao: "Avaliação com eletrocardiograma.",
        duracao: "1h",
        preco: 420,
      },
    ],
    equipe: [
      { id: "e1", nome: "Dra. Helena Braga", funcao: "Clínica geral" },
      { id: "e2", nome: "Dr. Paulo Ferrari", funcao: "Cardiologia" },
    ],
    faq: [
      {
        id: "f1",
        pergunta: "Atendem convênios?",
        resposta: "Sim, trabalhamos com os principais convênios nacionais.",
      },
    ],
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: "Agendar consulta",
        valor: "5562982771190",
        ativo: true,
      },
    ],
  });
  ligarSecoes(vitalis, [
    "apresentacao",
    "servicos",
    "equipe",
    "faq",
    "formulario",
    "localizacao",
    "horarios",
    "rodape",
  ]);

  return [cantina, navalha, ateliê, rota, studio, vitalis];
}
