import { extrasPorModelo } from "./demo-extras";
import { conteudoNovosModelos } from "./demo-novos";
import { conteudoModelosPremium } from "./demo-premium";
import { conteudoCardapioModelos, ehModeloCardapio } from "./cardapio-modelos";
import { criarSecoes, horariosPadrao, metricasPadrao, presetsModelo } from "./factory";
import { imagens } from "./images";
import { modeloPorId, modelos } from "./modelos";
import type { Site, TipoSecao } from "./types";

const conteudoPorModelo: Record<
  string,
  {
    nome: string;
    descricao: string;
    cidade: string;
    estado: string;
    whatsapp: string;
    instagram: string;
    endereco: string;
    secoes: TipoSecao[];
    produtos?: Site["produtos"];
    servicos?: Site["servicos"];
    equipe?: Site["equipe"];
    depoimentos?: Site["depoimentos"];
    faq?: Site["faq"];
    videos?: Site["videos"];
    /** Rótulo do botão principal da demonstração. */
    cta?: string;
    formulario?: Site["formulario"];
    galeria?: Site["galeria"];
    cupons?: Site["cupons"];
    logoFormato?: Site["aparencia"]["logoFormato"];
  }
> = {
  "restaurante-moderno": {
    nome: "Cantina do Vale",
    descricao: "Massas artesanais e forno a lenha no coração de Campinas.",
    cidade: "Campinas",
    estado: "SP",
    whatsapp: "5519974123388",
    instagram: "cantinadovale",
    endereco: "Rua das Oliveiras, 340 - Cambuí, Campinas - SP",
    secoes: [
      "apresentacao",
      "cardapio",
      "produtos",
      "galeria",
      "depoimentos",
      "cupom",
      "localizacao",
      "horarios",
      "rodape",
    ],
    produtos: [
      {
        id: "p1",
        nome: "Rondelli de funghi",
        descricao: "Massa fresca, creme de parmesão.",
        preco: 68.9,
        categoria: "Massas",
        variacoes: ["Individual", "Para dois"],
        imagem: imagens.restaurante,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Margherita napoletana",
        descricao: "Fermentação de 48h.",
        preco: 59,
        precoPromocional: 49.9,
        categoria: "Pizzas",
        variacoes: ["Média", "Grande"],
        imagem: imagens.hamburgueria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Tiramisù da casa",
        descricao: "Receita da nonna.",
        preco: 27,
        categoria: "Sobremesas",
        variacoes: [],
        disponivel: true,
        destaque: false,
      },
    ],
  },
  "hamburgueria-urbana": {
    nome: "Brasa 22",
    descricao: "Smash burgers na chapa, batata rústica e delivery até 23h.",
    cidade: "São Paulo",
    estado: "SP",
    whatsapp: "5511990012233",
    instagram: "brasa22",
    endereco: "Rua Augusta, 2210 - Consolação, São Paulo - SP",
    secoes: [
      "apresentacao",
      "produtos",
      "promocao",
      "depoimentos",
      "horarios",
      "localizacao",
      "rodape",
    ],
    produtos: [
      {
        id: "p1",
        nome: "Smash duplo",
        descricao: "Dois blends de 90g, cheddar e picles.",
        preco: 34.9,
        categoria: "Burgers",
        variacoes: ["Simples", "Duplo", "Triplo"],
        imagem: imagens.hamburgueria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Combo Brasa",
        descricao: "Burger + fritas + refri lata.",
        preco: 49.9,
        precoPromocional: 42.9,
        categoria: "Combos",
        variacoes: [],
        imagem: imagens.hamburgueria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Fritas com cheddar",
        descricao: "Porção generosa com bacon.",
        preco: 26,
        categoria: "Acompanhamentos",
        variacoes: [],
        disponivel: true,
        destaque: false,
      },
    ],
  },
  "loja-roupas": {
    nome: "Ateliê Lume",
    descricao: "Alfaiataria leve em pequenos lotes, feita em Belo Horizonte.",
    cidade: "Belo Horizonte",
    estado: "MG",
    whatsapp: "5531996542210",
    instagram: "atelie.lume",
    endereco: "Rua Fernandes Tourinho, 88 - Savassi, BH - MG",
    secoes: ["apresentacao", "produtos", "galeria", "depoimentos", "localizacao", "rodape"],
    produtos: [
      {
        id: "p1",
        nome: "Blazer linho areia",
        descricao: "Linho puro com forro em algodão.",
        preco: 489,
        categoria: "Alfaiataria",
        variacoes: ["P", "M", "G"],
        imagem: imagens.moda,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Calça pantalona",
        descricao: "Cintura alta, caimento fluido.",
        preco: 329,
        precoPromocional: 279,
        categoria: "Alfaiataria",
        variacoes: ["36", "38", "40"],
        imagem: imagens.moda,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Camisa seda off",
        descricao: "Toque frio, botões de madrepérola.",
        preco: 359,
        categoria: "Camisaria",
        variacoes: ["P", "M"],
        imagem: imagens.moda,
        disponivel: true,
        destaque: false,
      },
    ],
  },
  cosmeticos: {
    nome: "Pele Viva Cosméticos",
    descricao: "Skincare nacional, kits promocionais e frete grátis acima de R$ 199.",
    cidade: "Florianópolis",
    estado: "SC",
    whatsapp: "5548991234455",
    instagram: "peleviva",
    endereco: "Rua Bocaiúva, 500 - Centro, Florianópolis - SC",
    secoes: ["apresentacao", "produtos", "cupom", "depoimentos", "faq", "rodape"],
    produtos: [
      {
        id: "p1",
        nome: "Sérum vitamina C",
        descricao: "10% de ativo puro, 30ml.",
        preco: 139,
        categoria: "Rosto",
        variacoes: ["30ml"],
        imagem: imagens.cosmeticos,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Kit hidratação",
        descricao: "Sabonete, tônico e hidratante.",
        preco: 249,
        precoPromocional: 199,
        categoria: "Kits",
        variacoes: [],
        imagem: imagens.cosmeticos,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Protetor solar FPS 60",
        descricao: "Toque seco, sem oleosidade.",
        preco: 89,
        categoria: "Rosto",
        variacoes: [],
        imagem: imagens.cosmeticos,
        disponivel: true,
        destaque: false,
      },
    ],
  },
  "barbearia-premium": {
    nome: "Navalha de Ouro",
    descricao: "Barbearia clássica com atendimento por hora marcada.",
    cidade: "Niterói",
    estado: "RJ",
    whatsapp: "5521988124477",
    instagram: "navalhadeouro",
    endereco: "Av. Amaral Peixoto, 120 - Centro, Niterói - RJ",
    secoes: [
      "apresentacao",
      "servicos",
      "equipe",
      "galeria",
      "depoimentos",
      "horarios",
      "localizacao",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Corte social",
        descricao: "Máquina, tesoura e finalização.",
        duracao: "45 min",
        preco: 70,
        profissional: "Diego",
      },
      {
        id: "s2",
        nome: "Barba terapia",
        descricao: "Toalha quente, óleo e navalha.",
        duracao: "40 min",
        preco: 60,
        profissional: "Ricardo",
      },
      {
        id: "s3",
        nome: "Combo completo",
        descricao: "Corte + barba + sobrancelha.",
        duracao: "1h20",
        preco: 120,
        profissional: "Diego",
      },
    ],
    equipe: [
      { id: "e1", nome: "Diego Menezes", funcao: "Barbeiro-chefe" },
      { id: "e2", nome: "Ricardo Alves", funcao: "Barbeiro" },
    ],
  },
  "salao-beleza": {
    nome: "Studio Áurea",
    descricao: "Cabelo, unhas e estética avançada com hora marcada.",
    cidade: "Recife",
    estado: "PE",
    whatsapp: "5581994448877",
    instagram: "studioaurea",
    endereco: "Rua da Hora, 410 - Espinheiro, Recife - PE",
    secoes: ["apresentacao", "servicos", "equipe", "galeria", "depoimentos", "horarios", "rodape"],
    servicos: [
      {
        id: "s1",
        nome: "Corte + escova",
        descricao: "Lavagem, corte e finalização.",
        duracao: "1h",
        preco: 120,
        profissional: "Aline",
      },
      {
        id: "s2",
        nome: "Coloração",
        descricao: "Coloração completa com tratamento.",
        duracao: "2h30",
        preco: 320,
        profissional: "Bruna",
      },
      {
        id: "s3",
        nome: "Manicure e pedicure",
        descricao: "Esmaltação em gel inclusa.",
        duracao: "1h20",
        preco: 95,
        profissional: "Sandra",
      },
    ],
    equipe: [
      { id: "e1", nome: "Aline Cordeiro", funcao: "Hair stylist" },
      { id: "e2", nome: "Bruna Sales", funcao: "Colorista" },
    ],
  },
  clinica: {
    nome: "Clínica Vitalis",
    descricao: "Consultas, exames e acompanhamento multidisciplinar.",
    cidade: "Goiânia",
    estado: "GO",
    whatsapp: "5562982771190",
    instagram: "clinicavitalis",
    endereco: "Av. T-9, 1500 - Setor Bueno, Goiânia - GO",
    secoes: [
      "apresentacao",
      "servicos",
      "equipe",
      "faq",
      "formulario",
      "horarios",
      "localizacao",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Clínica geral",
        descricao: "Consulta de rotina.",
        duracao: "40 min",
        preco: 280,
      },
      {
        id: "s2",
        nome: "Nutrição",
        descricao: "Plano alimentar individualizado.",
        duracao: "50 min",
        preco: 240,
      },
      {
        id: "s3",
        nome: "Cardiologia",
        descricao: "Avaliação com eletrocardiograma.",
        duracao: "1h",
        preco: 420,
      },
    ],
    equipe: [
      {
        id: "e1",
        nome: "Dra. Renata Villas",
        funcao: "Clínica geral - CRM demonstração",
        foto: imagens.clinica,
      },
      { id: "e2", nome: "Dr. Paulo Menezes", funcao: "Cardiologia" },
      { id: "e3", nome: "Nut. Bruna Tavares", funcao: "Nutrição clínica" },
    ],
    faq: [
      {
        id: "f1",
        pergunta: "Atendem convênios?",
        resposta: "Sim, os principais convênios nacionais.",
      },
      {
        id: "f2",
        pergunta: "Como funciona o agendamento?",
        resposta:
          "Envie o formulário com a especialidade e a data desejada; a recepção confirma pelo WhatsApp.",
      },
      {
        id: "f3",
        pergunta: "Preciso levar exames anteriores?",
        resposta: "Sempre que possível leve exames dos últimos 12 meses para a primeira consulta.",
      },
    ],
  },
  "personal-trainer": {
    nome: "Marcos Vidal Treinamento",
    descricao: "Treinos personalizados presenciais e online para todos os níveis.",
    cidade: "Fortaleza",
    estado: "CE",
    whatsapp: "5585988776655",
    instagram: "marcosvidal.treino",
    endereco: "Av. Beira Mar, 3200 - Meireles, Fortaleza - CE",
    secoes: ["apresentacao", "servicos", "depoimentos", "galeria", "formulario", "rodape"],
    servicos: [
      {
        id: "s1",
        nome: "Consultoria online",
        descricao: "Treino atualizado a cada 4 semanas.",
        duracao: "Mensal",
        preco: 249,
      },
      {
        id: "s2",
        nome: "Personal presencial",
        descricao: "Acompanhamento individual.",
        duracao: "1h",
        preco: 130,
      },
    ],
  },
  fotografo: {
    nome: "Studio Clara Luz",
    descricao: "Ensaios editoriais, casamentos e fotografia de marca.",
    cidade: "Porto Alegre",
    estado: "RS",
    whatsapp: "5551983304412",
    instagram: "studioclaraluz",
    endereco: "Rua Padre Chagas, 210 - Porto Alegre - RS",
    secoes: ["apresentacao", "galeria", "servicos", "depoimentos", "formulario", "rodape"],
    servicos: [
      {
        id: "s1",
        nome: "Ensaio editorial",
        descricao: "2h de sessão, 30 fotos tratadas.",
        duracao: "2h",
        preco: 1200,
      },
      {
        id: "s2",
        nome: "Fotografia de marca",
        descricao: "Banco de imagens para redes.",
        duracao: "4h",
        preco: 2400,
      },
    ],
  },
  corretor: {
    nome: "Ricardo Paiva Imóveis",
    descricao: "Apartamentos e casas selecionados na zona sul de São Paulo.",
    cidade: "São Paulo",
    estado: "SP",
    whatsapp: "5511987001122",
    instagram: "ricardopaivaimoveis",
    endereco: "Av. Santo Amaro, 1800 - Brooklin, São Paulo - SP",
    secoes: ["apresentacao", "produtos", "depoimentos", "formulario", "localizacao", "rodape"],
    produtos: [
      {
        id: "p1",
        nome: "Apto 2 dorm. Brooklin",
        descricao: "68m², 1 vaga, lazer completo.",
        preco: 690000,
        categoria: "Apartamentos",
        variacoes: [],
        imagem: imagens.imoveis,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Cobertura Campo Belo",
        descricao: "140m², terraço com churrasqueira.",
        preco: 1480000,
        categoria: "Coberturas",
        variacoes: [],
        imagem: imagens.imoveis,
        disponivel: true,
        destaque: true,
      },
    ],
  },
  transportadora: {
    nome: "Rota Norte Transportes",
    descricao: "Cargas fracionadas e dedicadas para todo o Sul e Sudeste.",
    cidade: "Curitiba",
    estado: "PR",
    whatsapp: "5541991207788",
    instagram: "rotanortetransportes",
    endereco: "BR-116, km 92 - Curitiba - PR",
    secoes: ["apresentacao", "servicos", "formulario", "faq", "localizacao", "rodape"],
    servicos: [
      {
        id: "s1",
        nome: "Carga fracionada",
        descricao: "Coletas diárias na região metropolitana.",
        duracao: "24-72h",
        preco: 0,
      },
      {
        id: "s2",
        nome: "Carga dedicada",
        descricao: "Veículo exclusivo com rastreamento.",
        duracao: "Sob demanda",
        preco: 0,
      },
    ],
    faq: [
      {
        id: "f1",
        pergunta: "Quais regiões vocês atendem?",
        resposta: "Todo o Sul e Sudeste, com parceiros no Centro-Oeste.",
      },
    ],
  },
  "prestador-servicos": {
    nome: "Alves Manutenção Predial",
    descricao: "Elétrica, hidráulica e reparos gerais com garantia de 90 dias.",
    cidade: "Salvador",
    estado: "BA",
    whatsapp: "5571991234433",
    instagram: "alvesmanutencao",
    endereco: "Rua Silveira Martins, 90 - Cabula, Salvador - BA",
    secoes: ["apresentacao", "servicos", "depoimentos", "formulario", "faq", "rodape"],
    servicos: [
      {
        id: "s1",
        nome: "Instalação elétrica",
        descricao: "Tomadas, quadros e iluminação.",
        duracao: "Sob avaliação",
        preco: 180,
      },
      {
        id: "s2",
        nome: "Reparo hidráulico",
        descricao: "Vazamentos e trocas de louças.",
        duracao: "Sob avaliação",
        preco: 160,
      },
    ],
  },
  advocacia: {
    nome: "Marques & Prado Advocacia",
    descricao: "Escritório full service em direito trabalhista, civil e empresarial desde 2004.",
    cidade: "Curitiba",
    estado: "PR",
    whatsapp: "5541988774411",
    instagram: "marquesprado.adv",
    endereco: "Av. Cândido de Abreu, 660 - Centro Cívico, Curitiba - PR",
    secoes: [
      "apresentacao",
      "links",
      "servicos",
      "equipe",
      "depoimentos",
      "faq",
      "formulario",
      "localizacao",
      "horarios",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Direito trabalhista",
        descricao: "Rescisões, verbas, acordos e defesa em reclamatórias.",
        duracao: "Consulta 45 min",
        preco: 350,
        profissional: "Dra. Helena Marques",
      },
      {
        id: "s2",
        nome: "Direito de família",
        descricao: "Divórcio, guarda, pensão e inventário.",
        duracao: "Consulta 45 min",
        preco: 350,
        profissional: "Dr. Rafael Prado",
      },
      {
        id: "s3",
        nome: "Direito empresarial",
        descricao: "Contratos, societário e recuperação de crédito.",
        duracao: "Reunião 1h",
        preco: 520,
        profissional: "Dra. Helena Marques",
      },
      {
        id: "s4",
        nome: "Previdenciário",
        descricao: "Aposentadorias, revisões e benefícios do INSS.",
        duracao: "Consulta 45 min",
        preco: 300,
        profissional: "Dr. Caio Bertoldo",
      },
    ],
    equipe: [
      { id: "e1", nome: "Dra. Helena Marques", funcao: "Sócia — OAB/PR 38.221" },
      { id: "e2", nome: "Dr. Rafael Prado", funcao: "Sócio — OAB/PR 41.905" },
      { id: "e3", nome: "Dr. Caio Bertoldo", funcao: "Advogado previdenciário" },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Patrícia Nogueira",
        nota: 5,
        comentario:
          "Explicaram cada etapa do processo com clareza. Ganhei a causa em primeira instância.",
        data: "2026-05-12",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Empresa Vetor Ltda.",
        nota: 5,
        comentario: "Assessoria contratual impecável e resposta rápida no WhatsApp.",
        data: "2026-04-02",
        destaque: false,
      },
    ],
    faq: [
      {
        id: "f1",
        pergunta: "A primeira consulta é gratuita?",
        resposta:
          "A triagem inicial pelo WhatsApp é sem custo. A consulta técnica é agendada e tem honorário informado antes.",
      },
      {
        id: "f2",
        pergunta: "Vocês atendem online?",
        resposta:
          "Sim, atendemos por videoconferência em todo o Brasil, com assinatura digital de procuração.",
      },
      {
        id: "f3",
        pergunta: "Como acompanho meu processo?",
        resposta: "Enviamos atualizações por WhatsApp a cada movimentação relevante.",
      },
    ],
  },

  /* ---------------- demonstrações por segmento ---------------- */

  petshop: {
    nome: "Clube do Pet (demonstração)",
    descricao: "Banho, tosa e hidratação com transporte próprio na Zona Sul de Curitiba.",
    cidade: "Curitiba",
    estado: "PR",
    whatsapp: "5541996330011",
    instagram: "clubedopet.demo",
    endereco: "Rua Nicolau Maeder, 210 - Alto da Glória, Curitiba - PR",
    cta: "Agendar atendimento",
    secoes: [
      "apresentacao",
      "servicos",
      "produtos",
      "galeria",
      "equipe",
      "depoimentos",
      "formulario",
      "localizacao",
      "horarios",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Banho completo",
        descricao: "Shampoo neutro, secagem e perfume suave.",
        duracao: "1h30",
        preco: 79,
        profissional: "Marina Alves",
        imagem: imagens.petshop,
      },
      {
        id: "s2",
        nome: "Tosa higiênica",
        descricao: "Patinhas, barriga e focinho com acabamento na máquina.",
        duracao: "45 min",
        preco: 59,
        profissional: "Rafael Lopes",
      },
      {
        id: "s3",
        nome: "Hidratação de pelos",
        descricao: "Máscara nutritiva para pelagens longas e ressecadas.",
        duracao: "1h",
        preco: 95,
      },
      {
        id: "s4",
        nome: "Cuidados e taxi pet",
        descricao: "Corte de unhas, limpeza de ouvidos e busca em casa.",
        duracao: "Sob consulta",
        preco: 39,
      },
    ],
    produtos: [
      {
        id: "p1",
        nome: "Ração natural 2kg",
        descricao: "Sem corantes, indicada para cães adultos.",
        preco: 89.9,
        categoria: "Alimentação",
        variacoes: ["Frango", "Carne"],
        imagem: imagens.petshop,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Kit banho em casa",
        descricao: "Shampoo, condicionador e escova.",
        preco: 64.9,
        precoPromocional: 54.9,
        categoria: "Higiene",
        variacoes: [],
        disponivel: true,
        destaque: false,
      },
    ],
    equipe: [
      { id: "e1", nome: "Marina Alves", funcao: "Banhista e tosadora" },
      { id: "e2", nome: "Rafael Lopes", funcao: "Tosador pet" },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Carla (demonstração)",
        nota: 5,
        comentario: "Minha Lulu voltou cheirosa e super calma. Agendamento pelo WhatsApp é rápido.",
        data: "2026-06-02",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Tiago (demonstração)",
        nota: 5,
        comentario: "O taxi pet salvou minha semana. Atendimento cuidadoso com o Thor.",
        data: "2026-05-11",
        destaque: false,
      },
    ],
    formulario: {
      tipo: "agendamento",
      titulo: "Agende o atendimento do seu pet",
      campos: [
        { id: "c1", rotulo: "Seu nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "Nome do pet", tipo: "texto", obrigatorio: true },
        { id: "c3", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c4", rotulo: "Melhor data", tipo: "data", obrigatorio: false },
        { id: "c5", rotulo: "Serviço desejado", tipo: "textarea", obrigatorio: false },
      ],
    },
    faq: [
      {
        id: "f1",
        pergunta: "Vocês buscam o pet em casa?",
        resposta: "Sim, temos taxi pet para bairros próximos mediante agendamento.",
      },
    ],
  },

  odontologia: {
    nome: "Odonto Sorriso (demonstração)",
    descricao: "Clínica odontológica com avaliação gratuita, prevenção e estética dental.",
    cidade: "Belo Horizonte",
    estado: "MG",
    whatsapp: "5531988440022",
    instagram: "odontosorriso.demo",
    endereco: "Av. do Contorno, 4.500 - Funcionários, BH - MG",
    cta: "Agendar avaliação",
    logoFormato: "quadrado",
    secoes: [
      "apresentacao",
      "servicos",
      "equipe",
      "depoimentos",
      "faq",
      "formulario",
      "localizacao",
      "horarios",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Avaliação inicial",
        descricao: "Exame clínico, radiografia e plano de tratamento.",
        duracao: "40 min",
        preco: 0,
        profissional: "Dra. Helena Prado",
        imagem: imagens.odontologia,
      },
      {
        id: "s2",
        nome: "Limpeza e profilaxia",
        descricao: "Remoção de tártaro e aplicação de flúor.",
        duracao: "50 min",
        preco: 220,
        profissional: "Dra. Helena Prado",
      },
      {
        id: "s3",
        nome: "Clareamento dental",
        descricao: "Protocolo em consultório com moldeira de acompanhamento.",
        duracao: "3 sessões",
        preco: 1290,
      },
      {
        id: "s4",
        nome: "Tratamentos restauradores",
        descricao: "Restaurações, canal e próteses com materiais certificados.",
        duracao: "Sob avaliação",
        preco: 0,
      },
    ],
    equipe: [
      { id: "e1", nome: "Dra. Helena Prado", funcao: "Clínica geral e estética" },
      { id: "e2", nome: "Dr. Bruno Teixeira", funcao: "Implantodontia" },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Renata (demonstração)",
        nota: 5,
        comentario: "Explicaram cada etapa antes de começar. Saí sem dor e com tudo agendado.",
        data: "2026-06-21",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Paulo (demonstração)",
        nota: 5,
        comentario: "Clínica limpa, horário respeitado e orçamento transparente.",
        data: "2026-04-28",
        destaque: false,
      },
    ],
    formulario: {
      tipo: "agendamento",
      titulo: "Agende sua avaliação",
      campos: [
        { id: "c1", rotulo: "Nome completo", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Preferência de data", tipo: "data", obrigatorio: false },
        { id: "c4", rotulo: "O que você precisa?", tipo: "textarea", obrigatorio: false },
      ],
    },
    faq: [
      {
        id: "f1",
        pergunta: "Atendem convênios?",
        resposta: "Atendemos particular e os principais convênios; confirme pelo WhatsApp.",
      },
      {
        id: "f2",
        pergunta: "A avaliação tem custo?",
        resposta: "A primeira avaliação clínica é gratuita e sem compromisso.",
      },
    ],
  },

  mecanica: {
    nome: "Auto Prime Oficina (demonstração)",
    descricao: "Revisão, freios e diagnóstico eletrônico com orçamento aprovado por WhatsApp.",
    cidade: "Guarulhos",
    estado: "SP",
    whatsapp: "5511987552244",
    instagram: "autoprime.demo",
    endereco: "Av. Tiradentes, 1.180 - Vila Augusta, Guarulhos - SP",
    cta: "Solicitar orçamento",
    logoFormato: "quadrado",
    secoes: [
      "apresentacao",
      "servicos",
      "galeria",
      "faq",
      "formulario",
      "localizacao",
      "horarios",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Revisão completa",
        descricao: "Checklist de 32 itens com relatório fotográfico.",
        duracao: "3h",
        preco: 349,
        imagem: imagens.mecanica,
      },
      {
        id: "s2",
        nome: "Troca de óleo e filtros",
        descricao: "Óleo sintético e filtros originais.",
        duracao: "1h",
        preco: 289,
      },
      {
        id: "s3",
        nome: "Freios e suspensão",
        descricao: "Pastilhas, discos e alinhamento com teste em pista.",
        duracao: "2h30",
        preco: 0,
      },
      {
        id: "s4",
        nome: "Diagnóstico eletrônico",
        descricao: "Leitura de injeção e módulos com scanner automotivo.",
        duracao: "40 min",
        preco: 120,
      },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Marcos (demonstração)",
        nota: 5,
        comentario:
          "Mandaram o orçamento com fotos antes de mexer. Preço fechado e prazo cumprido.",
        data: "2026-06-09",
        destaque: true,
      },
    ],
    formulario: {
      tipo: "orcamento",
      titulo: "Solicite um orçamento",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Veículo e ano", tipo: "texto", obrigatorio: true },
        { id: "c4", rotulo: "Descreva o problema", tipo: "textarea", obrigatorio: false },
      ],
    },
    faq: [
      {
        id: "f1",
        pergunta: "Fazem orçamento sem compromisso?",
        resposta: "Sim. Avaliamos o veículo e enviamos o orçamento antes de qualquer serviço.",
      },
      {
        id: "f2",
        pergunta: "Qual a garantia dos serviços?",
        resposta: "90 dias de garantia em mão de obra e peças instaladas na oficina.",
      },
    ],
  },

  pizzaria: {
    nome: "Forno da Vila (demonstração)",
    descricao: "Pizzas de fermentação natural, combos e entrega em 40 minutos.",
    cidade: "Porto Alegre",
    estado: "RS",
    whatsapp: "5551997220033",
    instagram: "fornodavila.demo",
    endereco: "Rua Padre Chagas, 320 - Moinhos de Vento, Porto Alegre - RS",
    cta: "Fazer pedido",
    secoes: [
      "apresentacao",
      "cardapio",
      "produtos",
      "promocao",
      "cupom",
      "depoimentos",
      "formulario",
      "localizacao",
      "horarios",
      "rodape",
    ],
    produtos: [
      {
        id: "p1",
        nome: "Margherita da casa",
        descricao: "Molho de tomate italiano, muçarela de búfala e manjericão.",
        preco: 62,
        categoria: "Pizzas salgadas",
        variacoes: ["Média 6 fatias", "Grande 8 fatias"],
        imagem: imagens.pizzaria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Calabresa artesanal",
        descricao: "Calabresa defumada, cebola roxa e orégano fresco.",
        preco: 58,
        precoPromocional: 49.9,
        categoria: "Pizzas salgadas",
        variacoes: ["Média 6 fatias", "Grande 8 fatias"],
        imagem: imagens.pizzaria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Combo família",
        descricao: "Duas pizzas grandes + refrigerante 2L.",
        preco: 129,
        precoPromocional: 109,
        categoria: "Combos",
        variacoes: [],
        disponivel: true,
        destaque: true,
      },
      {
        id: "p4",
        nome: "Doce de Nutella",
        descricao: "Massa fina com Nutella e morangos.",
        preco: 69,
        categoria: "Pizzas doces",
        variacoes: ["Média", "Grande"],
        disponivel: true,
        destaque: false,
      },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Juliana (demonstração)",
        nota: 5,
        comentario: "Pedido pelo WhatsApp em dois minutos e a pizza chegou quentinha.",
        data: "2026-06-14",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Diego (demonstração)",
        nota: 5,
        comentario: "Massa leve, borda perfeita. O combo família vale muito a pena.",
        data: "2026-05-25",
        destaque: false,
      },
    ],
    cupons: [
      {
        id: "cp1",
        titulo: "Refrigerante grátis no combo",
        descricao: "Válido de segunda a quinta nos pedidos acima de R$ 100.",
        codigo: "FORNO2L",
        validade: "2026-12-31",
        ativo: true,
      },
    ],
    formulario: {
      tipo: "contato",
      titulo: "Faça seu pedido",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Endereço de entrega", tipo: "texto", obrigatorio: true },
        { id: "c4", rotulo: "Seu pedido", tipo: "textarea", obrigatorio: true },
      ],
    },
  },

  doceria: {
    nome: "Doce Afeto (demonstração)",
    descricao: "Bolos, doces finos e kits de festa feitos sob encomenda.",
    cidade: "Florianópolis",
    estado: "SC",
    whatsapp: "5548996110044",
    instagram: "doceafeto.demo",
    endereco: "Rua Bocaiúva, 1.120 - Centro, Florianópolis - SC",
    cta: "Fazer encomenda",
    secoes: [
      "apresentacao",
      "produtos",
      "galeria",
      "promocao",
      "cupom",
      "depoimentos",
      "formulario",
      "rodape",
    ],
    produtos: [
      {
        id: "p1",
        nome: "Bolo de festa 2 andares",
        descricao: "Recheio à escolha e acabamento em chantilly.",
        preco: 320,
        categoria: "Bolos",
        variacoes: ["25 fatias", "40 fatias"],
        imagem: imagens.doceria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p2",
        nome: "Kit 100 doces finos",
        descricao: "Brigadeiro belga, beijinho e casadinho.",
        preco: 240,
        precoPromocional: 210,
        categoria: "Kits",
        variacoes: [],
        imagem: imagens.doceria,
        disponivel: true,
        destaque: true,
      },
      {
        id: "p3",
        nome: "Torta holandesa",
        descricao: "Feita no dia, serve 8 pessoas.",
        preco: 98,
        categoria: "Tortas",
        variacoes: [],
        disponivel: true,
        destaque: false,
      },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Amanda (demonstração)",
        nota: 5,
        comentario: "O bolo ficou lindo e o sabor surpreendeu todo mundo na festa.",
        data: "2026-06-05",
        destaque: true,
      },
    ],
    cupons: [
      {
        id: "cp1",
        titulo: "10% na primeira encomenda",
        descricao: "Informe o código ao fechar o pedido pelo WhatsApp.",
        codigo: "DOCE10",
        validade: "2026-12-31",
        ativo: true,
      },
    ],
    formulario: {
      tipo: "orcamento",
      titulo: "Solicite sua encomenda",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Data de retirada", tipo: "data", obrigatorio: true },
        { id: "c4", rotulo: "O que você quer encomendar?", tipo: "textarea", obrigatorio: true },
      ],
    },
  },

  "eventos-festas": {
    nome: "Celebra Buffet (demonstração)",
    descricao: "Buffet completo para casamentos, aniversários e eventos corporativos.",
    cidade: "Ribeirão Preto",
    estado: "SP",
    whatsapp: "5516993880055",
    instagram: "celebrabuffet.demo",
    endereco: "Av. Braz Olaia Acosta, 900 - Jardim Califórnia, Ribeirão Preto - SP",
    cta: "Solicitar orçamento",
    secoes: [
      "apresentacao",
      "servicos",
      "galeria",
      "depoimentos",
      "faq",
      "formulario",
      "localizacao",
      "rodape",
    ],
    servicos: [
      {
        id: "s1",
        nome: "Casamentos",
        descricao: "Coquetel, jantar servido, equipe uniformizada e decoração de mesas.",
        duracao: "Pacote completo",
        preco: 0,
        imagem: imagens.eventos,
      },
      {
        id: "s2",
        nome: "Aniversários",
        descricao: "Buffet de finger food, mesa de doces e bar de bebidas.",
        duracao: "5h de evento",
        preco: 0,
      },
      {
        id: "s3",
        nome: "Eventos corporativos",
        descricao: "Coffee break, brunch e almoço executivo com nota fiscal.",
        duracao: "Sob demanda",
        preco: 0,
      },
    ],
    depoimentos: [
      {
        id: "d1",
        nome: "Letícia e Rafael (demonstração)",
        nota: 5,
        comentario: "Cuidaram de tudo no nosso casamento. Os convidados elogiaram a comida.",
        data: "2026-05-18",
        destaque: true,
      },
      {
        id: "d2",
        nome: "Grupo Vertt (demonstração)",
        nota: 5,
        comentario: "Coffee break impecável para 120 pessoas, montado no horário combinado.",
        data: "2026-04-02",
        destaque: false,
      },
    ],
    formulario: {
      tipo: "orcamento",
      titulo: "Solicite um orçamento",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Data do evento", tipo: "data", obrigatorio: true },
        { id: "c4", rotulo: "Número de convidados", tipo: "texto", obrigatorio: false },
        { id: "c5", rotulo: "Tipo de evento", tipo: "textarea", obrigatorio: false },
      ],
    },
    faq: [
      {
        id: "f1",
        pergunta: "Com quanta antecedência devo reservar?",
        resposta: "Recomendamos de 60 a 90 dias, principalmente para datas de fim de semana.",
      },
    ],
  },
  ...conteudoNovosModelos,
  ...conteudoModelosPremium,
  ...conteudoCardapioModelos,
};

const depoimentosGenericos: Site["depoimentos"] = [
  {
    id: "d1",
    nome: "Fernanda Rocha",
    nota: 5,
    comentario: "Atendimento rápido e resultado acima do esperado.",
    data: "2026-06-18",
    destaque: true,
  },
  {
    id: "d2",
    nome: "Luiz Henrique",
    nota: 5,
    comentario: "Fácil de encontrar tudo e falar pelo WhatsApp.",
    data: "2026-05-30",
    destaque: false,
  },
];

/** Ordena as seções da demonstração conforme a sequência definida no modelo. */
function ordenarSecoes(ordem: TipoSecao[], modeloId?: string): Site["secoes"] {
  const todas = criarSecoes(modeloId);
  const posicao = (tipo: TipoSecao) => {
    const i = ordem.indexOf(tipo);
    return i === -1 ? ordem.length + 1 : i;
  };
  return [...todas]
    .sort((a, b) => posicao(a.tipo) - posicao(b.tipo))
    .map((s) => ({ ...s, ativa: ordem.includes(s.tipo) || s.tipo === "links" }));
}

export function siteDoModelo(modeloId: string): Site {
  const modelo = modeloPorId(modeloId);
  const base = conteudoPorModelo["prestador-servicos"]!;
  const nomes: Record<string, string> = {
    petshop: "Clube do Pet",
    odontologia: "Odonto Sorriso",
    mecanica: "Auto Prime Oficina",
    pizzaria: "Forno da Vila",
    doceria: "Doce Afeto",
    "eventos-festas": "Celebra Buffet",
  };
  const alimentacao = modelo.segmento === "alimentacao";
  const proprio = conteudoPorModelo[modelo.id] ?? {
    ...base,
    nome: nomes[modelo.id] ?? modelo.nome,
    descricao: modelo.descricao,
    instagram: modelo.id.replace(/-/g, "."),
    secoes: presetsModelo[modelo.id]?.secoes ?? base.secoes,
    produtos: alimentacao
      ? [
          {
            id: "p1",
            nome: modelo.id === "pizzaria" ? "Pizza especial da casa" : "Produto em destaque",
            descricao: "Apresentação de exemplo para personalizar no editor.",
            preco: 49.9,
            categoria: modelo.id === "pizzaria" ? "Pizzas" : "Destaques",
            variacoes: modelo.id === "pizzaria" ? ["Média", "Grande"] : [],
            imagem: modelo.imagem,
            disponivel: true,
            destaque: true,
          },
        ]
      : [],
    servicos: alimentacao
      ? []
      : [
          {
            id: "s1",
            nome: modelo.destaque,
            descricao: "Serviço de exemplo para substituir pelas informações reais do negócio.",
            duracao: "Consulte",
            preco: 0,
            imagem: modelo.imagem,
          },
        ],
  };
  // Complementa os modelos mais antigos com CTA, depoimentos, formulário,
  // cupom, FAQ e galeria próprios do segmento, sem sobrescrever o que já existe.
  const c = { ...(extrasPorModelo[modelo.id] ?? {}), ...proprio };
  const agora = new Date().toISOString();
  return {
    id: `demo_${modelo.id}`,
    slug: modelo.id,
    status: "publicado",
    modeloId: modelo.id,
    criadoEm: agora,
    atualizadoEm: agora,
    cliente: {
      empresa: c.nome,
      segmento: modelo.segmento,
      responsavel: "Equipe " + c.nome,
      telefone: c.whatsapp,
      email: `contato@${modelo.id}.com.br`,
      cidade: c.cidade,
      estado: c.estado,
    },
    conteudo: {
      nome: c.nome,
      descricao: c.descricao,
      capa: modelo.imagem,
      telefone: c.whatsapp,
      whatsapp: c.whatsapp,
      email: `contato@${modelo.id}.com.br`,
      instagram: c.instagram,
      endereco: c.endereco,
      horarios: horariosPadrao(),
    },
    aparencia: {
      corPrimaria: modelo.paleta.primaria,
      corFundo: modelo.paleta.fundo,
      corTexto: modelo.paleta.texto,
      fonte:
        modelo.layout === "editorial" || modelo.layout === "minimalista" ? "elegante" : "moderna",
      raio: modelo.layout === "minimalista" ? 2 : modelo.layout === "colorido" ? 24 : 14,
      botao: modelo.layout === "minimalista" ? "contorno" : "solido",
      tema: ["#0", "#1", "#2"].some((p) => modelo.paleta.fundo.startsWith(p)) ? "escuro" : "claro",
      animacoes: true,
      espacamento: "confortavel",
      layout: modelo.layout,
      capaTipo: "imagem",
      logoFormato: c.logoFormato ?? "redondo",
    },
    secoes: ordenarSecoes(c.secoes, modelo.id),
    links: [
      {
        id: "l1",
        tipo: "whatsapp",
        titulo: c.cta ?? "Falar no WhatsApp",
        valor: c.whatsapp,
        ativo: true,
      },
      { id: "l2", tipo: "instagram", titulo: `@${c.instagram}`, valor: c.instagram, ativo: true },
      { id: "l3", tipo: "localizacao", titulo: "Como chegar", valor: c.endereco, ativo: true },
    ],
    produtos: c.produtos ?? [],
    servicos: c.servicos ?? [],
    galeria: c.galeria ?? [
      { id: "g1", url: modelo.imagem, titulo: c.nome },
      { id: "g2", url: imagens.moda, titulo: "Detalhes" },
      { id: "g3", url: imagens.salao, titulo: "Ambiente" },
    ],
    videos: c.videos ?? [],
    depoimentos: c.depoimentos ?? depoimentosGenericos,
    equipe: c.equipe ?? [],
    cupons: c.cupons ?? [
      {
        id: "cp1",
        titulo: "10% na primeira compra",
        descricao: "Use no atendimento pelo WhatsApp.",
        codigo: "BEMVINDO10",
        validade: "2026-12-31",
        ativo: true,
      },
    ],
    faq: c.faq ?? [
      {
        id: "f1",
        pergunta: "Como faço para contratar?",
        resposta: "Fale conosco pelo WhatsApp e retornamos em minutos.",
      },
    ],
    formulario: c.formulario ?? {
      tipo: "orcamento",
      titulo: "Peça um orçamento",
      campos: [
        { id: "c1", rotulo: "Nome", tipo: "texto", obrigatorio: true },
        { id: "c2", rotulo: "WhatsApp", tipo: "telefone", obrigatorio: true },
        { id: "c3", rotulo: "Mensagem", tipo: "textarea", obrigatorio: false },
      ],
    },
    seo: { titulo: c.nome, descricao: c.descricao, imagem: modelo.imagem, palavras: modelo.nome },
    integracoes: {
      googleAnalytics: "",
      metaPixel: "",
      dominio: "",
      googleMaps: "",
      whatsappApi: "",
    },
    metricas: metricasPadrao(80),
    ...(ehModeloCardapio(modelo.id)
      ? {
          comercio: {
            carrinho: true,
            taxaEntrega: 0,
            pedidoMinimo: 0,
          },
        }
      : {}),
    ...(modelo.id === "academia-studio"
      ? {
          agenda: {
            ativa: true,
            intervalo: 30,
            diasVisiveis: 14,
            observacao: "Escolha o melhor dia e horário para sua aula experimental.",
          },
        }
      : {}),
  };
}

export const sitesDeTodosModelos = () => modelos.map((m) => siteDoModelo(m.id));
