import { imagens } from "./images";
import type { Modelo } from "./types";

export const modelos: Modelo[] = [
  {
    id: "restaurante-moderno",
    nome: "Restaurante Moderno",
    segmento: "alimentacao",
    layout: "editorial",
    descricao: "Cardápio digital, reservas e pedidos pelo WhatsApp com clima de casa contemporânea.",
    destaque: "Cardápio + reserva",
    paleta: { fundo: "#12100e", texto: "#f7f3ec", primaria: "#e2b04a", suave: "#241f19" },
    imagem: imagens.restaurante,
  },
  {
    id: "hamburgueria-urbana",
    nome: "Hamburgueria Urbana",
    segmento: "alimentacao",
    layout: "urbano",
    descricao: "Visual noturno, combos em destaque e botão de pedido sempre à mão.",
    destaque: "Combos e delivery",
    paleta: { fundo: "#0e0e10", texto: "#fdfdfd", primaria: "#ff4d1c", suave: "#1b1b1f" },
    imagem: imagens.hamburgueria,
  },
  {
    id: "loja-roupas",
    nome: "Loja de Roupas",
    segmento: "comercio",
    layout: "catalogo",
    descricao: "Vitrine de coleções com variações de tamanho, promoções e Pix copia e cola.",
    destaque: "Catálogo com variações",
    paleta: { fundo: "#faf6f1", texto: "#201c18", primaria: "#c1633f", suave: "#efe6dc" },
    imagem: imagens.moda,
  },
  {
    id: "cosmeticos",
    nome: "Loja de Cosméticos",
    segmento: "comercio",
    layout: "colorido",
    descricao: "Produtos em destaque, kits promocionais e depoimentos de clientes.",
    destaque: "Kits e cupons",
    paleta: { fundo: "#fff6f7", texto: "#2a1b22", primaria: "#e8618c", suave: "#ffe6ec" },
    imagem: imagens.cosmeticos,
  },
  {
    id: "barbearia-premium",
    nome: "Barbearia Premium",
    segmento: "beleza",
    layout: "imersivo",
    descricao: "Agenda por profissional, portfólio antes e depois e clima escuro sofisticado.",
    destaque: "Agenda + portfólio",
    paleta: { fundo: "#141414", texto: "#f5f1e8", primaria: "#c9a227", suave: "#222020" },
    imagem: imagens.barbearia,
  },
  {
    id: "salao-beleza",
    nome: "Salão de Beleza",
    segmento: "beleza",
    layout: "cards",
    descricao: "Serviços por categoria, equipe e agendamento rápido em cards claros.",
    destaque: "Serviços e equipe",
    paleta: { fundo: "#fff8f9", texto: "#2c2226", primaria: "#d2708f", suave: "#ffe9ef" },
    imagem: imagens.salao,
  },
  {
    id: "clinica",
    nome: "Clínica e Consultório",
    segmento: "saude",
    layout: "corporativo",
    descricao: "Especialidades, convênios, horários e agendamento com aparência de confiança.",
    destaque: "Convênios e agenda",
    paleta: { fundo: "#f6f9fb", texto: "#132029", primaria: "#1f7a8c", suave: "#e3eff4" },
    imagem: imagens.clinica,
  },
  {
    id: "personal-trainer",
    nome: "Personal Trainer",
    segmento: "profissionais",
    layout: "urbano",
    descricao: "Planos de treino, resultados de alunos e contato direto pelo WhatsApp.",
    destaque: "Planos e resultados",
    paleta: { fundo: "#0f1210", texto: "#f2fff4", primaria: "#b8ff3c", suave: "#1a1f1b" },
    imagem: imagens.fitness,
  },
  {
    id: "fotografo",
    nome: "Fotógrafo",
    segmento: "profissionais",
    layout: "minimalista",
    descricao: "Portfólio em destaque, pacotes e formulário de orçamento discreto.",
    destaque: "Portfólio e pacotes",
    paleta: { fundo: "#101010", texto: "#f0eeea", primaria: "#e8e2d4", suave: "#1c1c1c" },
    imagem: imagens.fotografo,
  },
  {
    id: "corretor",
    nome: "Corretor de Imóveis",
    segmento: "imoveis",
    layout: "catalogo",
    descricao: "Imóveis disponíveis com fotos, valores e contato imediato para visita.",
    destaque: "Vitrine de imóveis",
    paleta: { fundo: "#f7f7f4", texto: "#16211c", primaria: "#2f6f4e", suave: "#e6ece7" },
    imagem: imagens.imoveis,
  },
  {
    id: "transportadora",
    nome: "Transportadora",
    segmento: "transporte",
    layout: "corporativo",
    descricao: "Cotação de frete, regiões atendidas e tipos de veículos disponíveis.",
    destaque: "Cotação de frete",
    paleta: { fundo: "#0f1620", texto: "#eef4fb", primaria: "#ff9f1c", suave: "#182231" },
    imagem: imagens.transporte,
  },
  {
    id: "advocacia",
    nome: "Advocacia e Consultoria Jurídica",
    segmento: "profissionais",
    layout: "corporativo",
    descricao:
      "Áreas de atuação, equipe de advogados, artigos e agendamento de consulta com ar institucional.",
    destaque: "Áreas de atuação + consulta",
    paleta: { fundo: "#0f1418", texto: "#f2efe8", primaria: "#b8935a", suave: "#1a2026" },
    imagem: imagens.advocacia,
  },
  {
    id: "prestador-servicos",
    nome: "Prestador de Serviços",
    segmento: "servicos",
    layout: "cards",
    descricao: "Lista de serviços, área de atendimento e orçamento em poucos toques.",
    destaque: "Orçamento rápido",
    paleta: { fundo: "#fbfaf7", texto: "#1b1d1a", primaria: "#356859", suave: "#e9eee9" },
    imagem: imagens.servicos,
  },
];

export const modeloPorId = (id: string) => modelos.find((m) => m.id === id) ?? modelos[0]!;
