import { imagens } from "./images";
import { modelosCardapio } from "./cardapio-modelos";
import type { Modelo } from "./types";

export const modelos: Modelo[] = [
  {
    id: "restaurante-moderno",
    nome: "Restaurante Moderno",
    segmento: "alimentacao",
    layout: "editorial",
    descricao:
      "Cardápio digital, reservas e pedidos pelo WhatsApp com clima de casa contemporânea.",
    destaque: "Cardápio + reserva",
    paleta: { fundo: "#12100e", texto: "#f7f3ec", primaria: "#e2b04a", suave: "#241f19" },
    imagem: imagens.restaurante,
  },
  {
    id: "hamburgueria-urbana",
    nome: "Hamburgueria Urbana",
    segmento: "alimentacao",
    layout: "urbano",
    descricao: "Visual noturno, combos em destaque e botão de pedido sempre à mão.",
    destaque: "Combos e delivery",
    paleta: { fundo: "#0e0e10", texto: "#fdfdfd", primaria: "#ff4d1c", suave: "#1b1b1f" },
    imagem: imagens.hamburgueria,
  },
  {
    id: "loja-roupas",
    nome: "Loja de Roupas",
    segmento: "comercio",
    layout: "catalogo",
    descricao: "Vitrine de coleções com variações de tamanho, promoções e pedidos pelo WhatsApp.",
    destaque: "Catálogo com variações",
    paleta: { fundo: "#faf6f1", texto: "#201c18", primaria: "#c1633f", suave: "#efe6dc" },
    imagem: imagens.moda,
  },
  {
    id: "cosmeticos",
    nome: "Loja de Cosméticos",
    segmento: "comercio",
    layout: "colorido",
    descricao: "Produtos em destaque, kits promocionais e depoimentos de clientes.",
    destaque: "Kits e cupons",
    paleta: { fundo: "#fff6f7", texto: "#2a1b22", primaria: "#e8618c", suave: "#ffe6ec" },
    imagem: imagens.cosmeticos,
  },
  {
    id: "barbearia-premium",
    nome: "Barbearia Premium",
    segmento: "beleza",
    layout: "imersivo",
    descricao: "Agenda por profissional, portfólio antes e depois e clima escuro sofisticado.",
    destaque: "Agenda + portfólio",
    paleta: { fundo: "#141414", texto: "#f5f1e8", primaria: "#c9a227", suave: "#222020" },
    imagem: imagens.barbearia,
  },
  {
    id: "salao-beleza",
    nome: "Salão de Beleza",
    segmento: "beleza",
    layout: "cards",
    descricao: "Serviços por categoria, equipe e agendamento rápido em cards claros.",
    destaque: "Serviços e equipe",
    paleta: { fundo: "#fff8f9", texto: "#2c2226", primaria: "#d2708f", suave: "#ffe9ef" },
    imagem: imagens.salao,
  },
  {
    id: "clinica",
    nome: "Clínica e Consultório",
    segmento: "saude",
    layout: "corporativo",
    descricao: "Especialidades, convênios, horários e agendamento com aparência de confiança.",
    destaque: "Convênios e agenda",
    paleta: { fundo: "#f6f9fb", texto: "#132029", primaria: "#1f7a8c", suave: "#e3eff4" },
    imagem: imagens.clinica,
  },
  {
    id: "personal-trainer",
    nome: "Personal Trainer",
    segmento: "profissionais",
    layout: "urbano",
    descricao: "Planos de treino, resultados de alunos e contato direto pelo WhatsApp.",
    destaque: "Planos e resultados",
    paleta: { fundo: "#0f1210", texto: "#f2fff4", primaria: "#b8ff3c", suave: "#1a1f1b" },
    imagem: imagens.fitness,
  },
  {
    id: "fotografo",
    nome: "Fotógrafo",
    segmento: "profissionais",
    layout: "minimalista",
    descricao: "Portfólio em destaque, pacotes e formulário de orçamento discreto.",
    destaque: "Portfólio e pacotes",
    paleta: { fundo: "#101010", texto: "#f0eeea", primaria: "#e8e2d4", suave: "#1c1c1c" },
    imagem: imagens.fotografo,
  },
  {
    id: "corretor",
    nome: "Corretor de Imóveis",
    segmento: "imoveis",
    layout: "catalogo",
    descricao: "Imóveis disponíveis com fotos, valores e contato imediato para visita.",
    destaque: "Vitrine de imóveis",
    paleta: { fundo: "#f7f7f4", texto: "#16211c", primaria: "#2f6f4e", suave: "#e6ece7" },
    imagem: imagens.imoveis,
  },
  {
    id: "transportadora",
    nome: "Transportadora",
    segmento: "transporte",
    layout: "corporativo",
    descricao: "Cotação de frete, regiões atendidas e tipos de veículos disponíveis.",
    destaque: "Cotação de frete",
    paleta: { fundo: "#0f1620", texto: "#eef4fb", primaria: "#ff9f1c", suave: "#182231" },
    imagem: imagens.transporte,
  },
  {
    id: "advocacia",
    nome: "Advocacia e Consultoria Jurídica",
    segmento: "profissionais",
    layout: "corporativo",
    descricao:
      "Áreas de atuação, equipe de advogados, artigos e agendamento de consulta com ar institucional.",
    destaque: "Áreas de atuação + consulta",
    paleta: { fundo: "#0f1418", texto: "#f2efe8", primaria: "#b8935a", suave: "#1a2026" },
    imagem: imagens.advocacia,
  },
  {
    id: "prestador-servicos",
    nome: "Prestador de Serviços",
    segmento: "servicos",
    layout: "cards",
    descricao: "Lista de serviços, área de atendimento e orçamento em poucos toques.",
    destaque: "Orçamento rápido",
    paleta: { fundo: "#fbfaf7", texto: "#1b1d1a", primaria: "#356859", suave: "#e9eee9" },
    imagem: imagens.servicos,
  },
  {
    id: "petshop",
    nome: "Pet Shop e Banho e Tosa",
    segmento: "servicos",
    layout: "cards",
    descricao: "Serviços de banho, tosa e produtos com agendamento rápido pelo WhatsApp.",
    destaque: "Agenda + produtos",
    paleta: { fundo: "#fbf7f2", texto: "#20211d", primaria: "#2f9e8f", suave: "#e7f2ef" },
    imagem: imagens.petshop,
  },
  {
    id: "odontologia",
    nome: "Clínica Odontológica",
    segmento: "saude",
    layout: "corporativo",
    descricao: "Tratamentos, convênios, equipe e agendamento com aparência limpa e confiável.",
    destaque: "Tratamentos + agenda",
    paleta: { fundo: "#f5fbfd", texto: "#10222b", primaria: "#2aa6c4", suave: "#e0f2f8" },
    imagem: imagens.odontologia,
  },
  {
    id: "mecanica",
    nome: "Oficina Mecânica",
    segmento: "servicos",
    layout: "urbano",
    descricao: "Serviços por veículo, orçamento rápido e localização da oficina.",
    destaque: "Orçamento + serviços",
    paleta: { fundo: "#111417", texto: "#f3f5f7", primaria: "#f2a007", suave: "#1c2126" },
    imagem: imagens.mecanica,
  },
  {
    id: "pizzaria",
    nome: "Pizzaria e Delivery",
    segmento: "alimentacao",
    layout: "catalogo",
    descricao: "Cardápio com tamanhos e sabores, promoções e pedido direto no WhatsApp.",
    destaque: "Cardápio + delivery",
    paleta: { fundo: "#17110d", texto: "#faf3ea", primaria: "#d4462f", suave: "#241a14" },
    imagem: imagens.pizzaria,
  },
  {
    id: "doceria",
    nome: "Doceria e Confeitaria",
    segmento: "alimentacao",
    layout: "colorido",
    descricao: "Vitrine de doces, encomendas por data e cupons para clientes fiéis.",
    destaque: "Encomendas + cupons",
    paleta: { fundo: "#fff8fa", texto: "#2b1f26", primaria: "#d4638d", suave: "#ffe7f0" },
    imagem: imagens.doceria,
  },
  {
    id: "eventos-festas",
    nome: "Buffet e Eventos",
    segmento: "eventos",
    layout: "imersivo",
    descricao: "Pacotes de festa, galeria de eventos e formulário de orçamento por data.",
    destaque: "Pacotes + orçamento",
    paleta: { fundo: "#14101a", texto: "#f6f1fa", primaria: "#b07cff", suave: "#211a2b" },
    imagem: imagens.eventos,
  },
  {
    id: "academia-studio",
    nome: "Academia e Studio de Pilates",
    segmento: "saude",
    layout: "cards",
    descricao:
      "Modalidades, planos, grade de horários, professores e aula experimental com agendamento.",
    destaque: "Planos + aula experimental",
    paleta: { fundo: "#f7f9f6", texto: "#16201a", primaria: "#3f7d4f", suave: "#e6efe6" },
    imagem: imagens.academia,
  },
  {
    id: "tattoo-studio",
    nome: "Estúdio de Tatuagem",
    segmento: "beleza",
    layout: "imersivo",
    descricao:
      "Portfólio por estilo, artistas do estúdio, cuidados pós-tattoo e orçamento por referência.",
    destaque: "Portfólio + orçamento",
    paleta: { fundo: "#0c0c0d", texto: "#f4f1ee", primaria: "#c2413a", suave: "#171718" },
    imagem: imagens.tattoo,
  },
  {
    id: "construcao-arquitetura",
    nome: "Construção e Arquitetura",
    segmento: "servicos",
    layout: "corporativo",
    descricao:
      "Serviços, obras realizadas, processo de trabalho por etapas e solicitação de orçamento.",
    destaque: "Obras + orçamento",
    paleta: { fundo: "#f6f5f2", texto: "#1a1c1e", primaria: "#c46a1f", suave: "#e9e6e0" },
    imagem: imagens.construcao,
  },
  {
    id: "pousada-hotel",
    nome: "Pousada e Hospedagem",
    segmento: "eventos",
    layout: "editorial",
    descricao:
      "Acomodações com valores, galeria, comodidades, localização e consulta de disponibilidade.",
    destaque: "Acomodações + reserva",
    paleta: { fundo: "#fbf7f1", texto: "#1d2521", primaria: "#0f7d76", suave: "#e7f0ec" },
    imagem: imagens.pousada,
  },
  {
    id: "nutricionista-clinico",
    nome: "Nutricionista e Clínica de Nutrição",
    segmento: "saude",
    layout: "cards",
    descricao: "Consultas, planos alimentares e acompanhamento com agenda integrada.",
    destaque: "Consulta + agenda",
    paleta: { fundo: "#f6faf6", texto: "#15211a", primaria: "#3d8b5f", suave: "#e5f0e8" },
    imagem: imagens.nutricao,
  },
  {
    id: "psicologia-terapia",
    nome: "Psicologia e Terapia",
    segmento: "saude",
    layout: "minimalista",
    descricao: "Abordagens, equipe, sessões online e agendamento discreto e acolhedor.",
    destaque: "Sessões + agenda",
    paleta: { fundo: "#faf8f5", texto: "#20211f", primaria: "#7c6a58", suave: "#efeae3" },
    imagem: imagens.psicologia,
  },
  {
    id: "estetica-spa",
    nome: "Estética e Spa",
    segmento: "beleza",
    layout: "editorial",
    descricao: "Protocolos faciais, massagens e day spa com clima de descanso premium.",
    destaque: "Protocolos + reserva",
    paleta: { fundo: "#fdf8f3", texto: "#241d18", primaria: "#b8894f", suave: "#f3e7da" },
    imagem: imagens.spa,
  },
  {
    id: "nail-designer",
    nome: "Nail Designer",
    segmento: "beleza",
    layout: "colorido",
    descricao: "Portfólio de unhas, tabela de serviços e agendamento em poucos toques.",
    destaque: "Portfólio + agenda",
    paleta: { fundo: "#fff7fa", texto: "#2b1e24", primaria: "#e0708f", suave: "#ffe6ee" },
    imagem: imagens.nail,
  },
  {
    id: "escola-idiomas",
    nome: "Escola de Idiomas",
    segmento: "profissionais",
    layout: "cards",
    descricao: "Cursos, níveis, planos e teste de nivelamento gratuito.",
    destaque: "Cursos + nivelamento",
    paleta: { fundo: "#f5f8ff", texto: "#131a2a", primaria: "#3559c7", suave: "#e3eaff" },
    imagem: imagens.idiomas,
  },
  {
    id: "autoescola",
    nome: "Autoescola e CFC",
    segmento: "servicos",
    layout: "corporativo",
    descricao: "Categorias, etapas do processo, valores e simulação de matrícula.",
    destaque: "Habilitação + matrícula",
    paleta: { fundo: "#f7f8fa", texto: "#161a1f", primaria: "#1f6fd0", suave: "#e5ebf3" },
    imagem: imagens.autoescola,
  },
  {
    id: "contabilidade",
    nome: "Contabilidade e Consultoria",
    segmento: "profissionais",
    layout: "corporativo",
    descricao: "Serviços contábeis, planos mensais e proposta rápida para abrir empresa.",
    destaque: "Planos + proposta",
    paleta: { fundo: "#f6f8fb", texto: "#101822", primaria: "#1e5f9e", suave: "#e2ebf4" },
    imagem: imagens.contabilidade,
  },
  {
    id: "agencia-marketing",
    nome: "Agência de Marketing",
    segmento: "profissionais",
    layout: "urbano",
    descricao: "Serviços, cases, resultados e diagnóstico gratuito com clima digital.",
    destaque: "Cases + diagnóstico",
    paleta: { fundo: "#0c0f14", texto: "#f1f5fa", primaria: "#5b8cff", suave: "#161b23" },
    imagem: imagens.agencia,
  },
  {
    id: "floricultura",
    nome: "Floricultura e Presentes",
    segmento: "comercio",
    layout: "colorido",
    descricao: "Vitrine de buquês e arranjos com entrega no mesmo dia e cupons.",
    destaque: "Vitrine + entrega",
    paleta: { fundo: "#fff9f9", texto: "#261d20", primaria: "#c2456b", suave: "#ffe8ea" },
    imagem: imagens.floricultura,
  },
  {
    id: "assistencia-tecnica",
    nome: "Assistência Técnica",
    segmento: "servicos",
    layout: "cards",
    descricao: "Serviços por aparelho, garantia, prazos e orçamento gratuito.",
    destaque: "Orçamento + garantia",
    paleta: { fundo: "#f5f7f9", texto: "#121820", primaria: "#0f7ba8", suave: "#e2eef4" },
    imagem: imagens.assistencia,
  },
  {
    id: "estetica-automotiva",
    nome: "Estética Automotiva",
    segmento: "servicos",
    layout: "imersivo",
    descricao: "Polimento, vitrificação e higienização com visual escuro e sofisticado.",
    destaque: "Detalhamento + agenda",
    paleta: { fundo: "#0b0c0e", texto: "#f2f4f6", primaria: "#d9b25a", suave: "#15171a" },
    imagem: imagens.automotiva,
  },
  {
    id: "turismo-passeios",
    nome: "Turismo e Passeios",
    segmento: "eventos",
    layout: "editorial",
    descricao: "Passeios, transfers e roteiros com valores e reserva pelo WhatsApp.",
    destaque: "Roteiros + reserva",
    paleta: { fundo: "#f4fbfc", texto: "#0f2229", primaria: "#0f8ba8", suave: "#dff1f5" },
    imagem: imagens.turismo,
  },
  ...modelosCardapio,
];

/** Ponto de partida em branco: estrutura mínima para montar tudo do zero. */
export const modeloPersonalizado: Modelo = {
  id: "personalizado",
  nome: "Personalizado (do zero)",
  segmento: "servicos",
  layout: "minimalista",
  descricao:
    "Comece com uma base limpa: apenas apresentação, links e rodapé. Você ativa e monta as demais seções do seu jeito.",
  destaque: "Estrutura em branco",
  paleta: { fundo: "#ffffff", texto: "#141414", primaria: "#111111", suave: "#f2f2f2" },
  imagem: imagens.servicos,
};

/** Lista usada na criação e na edição (inclui o modelo em branco). */
export const modelosCriacao: Modelo[] = [modeloPersonalizado, ...modelos];

export const modeloPorId = (id: string) =>
  id === modeloPersonalizado.id
    ? modeloPersonalizado
    : (modelos.find((m) => m.id === id) ?? modelos[0]!);
