/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento.$token'
import { Route as DemonstracaoModeloRouteImport } from './routes/demonstracao.$modelo'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelClientesRouteImport } from './routes/painel.clientes'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelEstatisticasRouteImport } from './routes/painel.estatisticas'
import { Route as PainelMidiasRouteImport } from './routes/painel.midias'
import { Route as PainelModelosRouteImport } from './routes/painel.modelos'
import { Route as PainelNovoRouteImport } from './routes/painel.novo'
import { Route as PainelSolicitacoesRouteImport } from './routes/painel.solicitacoes'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as PainelAdminIndexRouteImport } from './routes/painel.admin.index'
import { Route as PainelAdminPapeisRouteImport } from './routes/painel.admin.papeis'
import { Route as PainelEditorIdRouteImport } from './routes/painel.editor.$id'
import { Route as ApiPublicManifestSlugRouteImport } from './routes/api/public/manifest.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoModeloRoute = DemonstracaoModeloRouteImport.update({
  id: '/demonstracao/$modelo',
  path: '/demonstracao/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstatisticasRoute = PainelEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMidiasRoute = PainelMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => PainelRoute,
} as any)
const PainelModelosRoute = PainelModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNovoRoute = PainelNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSolicitacoesRoute = PainelSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => PainelRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAdminIndexRoute = PainelAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAdminPapeisRoute = PainelAdminPapeisRouteImport.update({
  id: '/admin/papeis',
  path: '/admin/papeis',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEditorIdRoute = PainelEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => PainelRoute,
} as any)
const ApiPublicManifestSlugRoute = ApiPublicManifestSlugRouteImport.update({
  id: '/api/public/manifest/$slug',
  path: '/api/public/manifest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/midias': typeof PainelMidiasRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/novo': typeof PainelNovoRoute
  '/painel/solicitacoes': typeof PainelSolicitacoesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/admin/papeis': typeof PainelAdminPapeisRoute
  '/painel/editor/$id': typeof PainelEditorIdRoute
  '/painel/admin/': typeof PainelAdminIndexRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/midias': typeof PainelMidiasRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/novo': typeof PainelNovoRoute
  '/painel/solicitacoes': typeof PainelSolicitacoesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/painel': typeof PainelIndexRoute
  '/painel/admin/papeis': typeof PainelAdminPapeisRoute
  '/painel/editor/$id': typeof PainelEditorIdRoute
  '/painel/admin': typeof PainelAdminIndexRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/clientes': typeof PainelClientesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/midias': typeof PainelMidiasRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/novo': typeof PainelNovoRoute
  '/painel/solicitacoes': typeof PainelSolicitacoesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/admin/papeis': typeof PainelAdminPapeisRoute
  '/painel/editor/$id': typeof PainelEditorIdRoute
  '/painel/admin/': typeof PainelAdminIndexRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/login'
    | '/modelos'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/agendamento/$token'
    | '/demonstracao/$modelo'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/midias'
    | '/painel/modelos'
    | '/painel/novo'
    | '/painel/solicitacoes'
    | '/site/$slug'
    | '/painel/'
    | '/painel/admin/papeis'
    | '/painel/editor/$id'
    | '/painel/admin/'
    | '/api/public/manifest/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/login'
    | '/modelos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/agendamento/$token'
    | '/demonstracao/$modelo'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/midias'
    | '/painel/modelos'
    | '/painel/novo'
    | '/painel/solicitacoes'
    | '/site/$slug'
    | '/painel'
    | '/painel/admin/papeis'
    | '/painel/editor/$id'
    | '/painel/admin'
    | '/api/public/manifest/$slug'
  id:
    | '__root__'
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/login'
    | '/modelos'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/agendamento/$token'
    | '/demonstracao/$modelo'
    | '/painel/agenda'
    | '/painel/clientes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/midias'
    | '/painel/modelos'
    | '/painel/novo'
    | '/painel/solicitacoes'
    | '/site/$slug'
    | '/painel/'
    | '/painel/admin/papeis'
    | '/painel/editor/$id'
    | '/painel/admin/'
    | '/api/public/manifest/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRoute
  PainelRoute: typeof PainelRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  TermosRoute: typeof TermosRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
  DemonstracaoModeloRoute: typeof DemonstracaoModeloRoute
  SiteSlugRoute: typeof SiteSlugRoute
  ApiPublicManifestSlugRoute: typeof ApiPublicManifestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao/$modelo': {
      id: '/demonstracao/$modelo'
      path: '/demonstracao/$modelo'
      fullPath: '/demonstracao/$modelo'
      preLoaderRoute: typeof DemonstracaoModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/clientes': {
      id: '/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/estatisticas': {
      id: '/painel/estatisticas'
      path: '/estatisticas'
      fullPath: '/painel/estatisticas'
      preLoaderRoute: typeof PainelEstatisticasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/midias': {
      id: '/painel/midias'
      path: '/midias'
      fullPath: '/painel/midias'
      preLoaderRoute: typeof PainelMidiasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/modelos': {
      id: '/painel/modelos'
      path: '/modelos'
      fullPath: '/painel/modelos'
      preLoaderRoute: typeof PainelModelosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/novo': {
      id: '/painel/novo'
      path: '/novo'
      fullPath: '/painel/novo'
      preLoaderRoute: typeof PainelNovoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/solicitacoes': {
      id: '/painel/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/painel/solicitacoes'
      preLoaderRoute: typeof PainelSolicitacoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/admin/': {
      id: '/painel/admin/'
      path: '/admin'
      fullPath: '/painel/admin/'
      preLoaderRoute: typeof PainelAdminIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/admin/papeis': {
      id: '/painel/admin/papeis'
      path: '/admin/papeis'
      fullPath: '/painel/admin/papeis'
      preLoaderRoute: typeof PainelAdminPapeisRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/editor/$id': {
      id: '/painel/editor/$id'
      path: '/editor/$id'
      fullPath: '/painel/editor/$id'
      preLoaderRoute: typeof PainelEditorIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/api/public/manifest/$slug': {
      id: '/api/public/manifest/$slug'
      path: '/api/public/manifest/$slug'
      fullPath: '/api/public/manifest/$slug'
      preLoaderRoute: typeof ApiPublicManifestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelEstatisticasRoute: typeof PainelEstatisticasRoute
  PainelMidiasRoute: typeof PainelMidiasRoute
  PainelModelosRoute: typeof PainelModelosRoute
  PainelNovoRoute: typeof PainelNovoRoute
  PainelSolicitacoesRoute: typeof PainelSolicitacoesRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelAdminPapeisRoute: typeof PainelAdminPapeisRoute
  PainelEditorIdRoute: typeof PainelEditorIdRoute
  PainelAdminIndexRoute: typeof PainelAdminIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelClientesRoute: PainelClientesRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelEstatisticasRoute: PainelEstatisticasRoute,
  PainelMidiasRoute: PainelMidiasRoute,
  PainelModelosRoute: PainelModelosRoute,
  PainelNovoRoute: PainelNovoRoute,
  PainelSolicitacoesRoute: PainelSolicitacoesRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelAdminPapeisRoute: PainelAdminPapeisRoute,
  PainelEditorIdRoute: PainelEditorIdRoute,
  PainelAdminIndexRoute: PainelAdminIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRoute,
  PainelRoute: PainelRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  TermosRoute: TermosRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
  DemonstracaoModeloRoute: DemonstracaoModeloRoute,
  SiteSlugRoute: SiteSlugRoute,
  ApiPublicManifestSlugRoute: ApiPublicManifestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
