/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as DemonstracaoModeloRouteImport } from './routes/demonstracao.$modelo'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoModeloRoute = DemonstracaoModeloRouteImport.update({
  id: '/demonstracao/$modelo',
  path: '/demonstracao/$modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modelos': typeof ModelosRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modelos': typeof ModelosRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modelos': typeof ModelosRoute
  '/demonstracao/$modelo': typeof DemonstracaoModeloRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modelos' | '/demonstracao/$modelo' | '/site/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modelos' | '/demonstracao/$modelo' | '/site/$slug'
  id: '__root__' | '/' | '/modelos' | '/demonstracao/$modelo' | '/site/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelosRoute: typeof ModelosRoute
  DemonstracaoModeloRoute: typeof DemonstracaoModeloRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao/$modelo': {
      id: '/demonstracao/$modelo'
      path: '/demonstracao/$modelo'
      fullPath: '/demonstracao/$modelo'
      preLoaderRoute: typeof DemonstracaoModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelosRoute: ModelosRoute,
  DemonstracaoModeloRoute: DemonstracaoModeloRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
