// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vsnvzgcotnrxrbztrxlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbnZ6Z2NvdG5yeHJienRyeGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4MjI3NTEsImV4cCI6MjEwMjM5ODc1MX0.zQBAZuq1Zk2eEWTaoT9hQtoe84UnN-m7uN6Y5FPQqmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Cada janela/aba mantém sua própria sessão. Isso evita que criar ou entrar
    // com outra conta em uma segunda janela troque silenciosamente a conta em uso.
    // A sessão ainda sobrevive a recarregamentos da mesma aba.
    storage: typeof window !== "undefined" ? sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
