// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { sessaoDaAba } from "./tab-session";

const SUPABASE_URL = "https://vsnvzgcotnrxrbztrxlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbnZ6Z2NvdG5yeHJienRyeGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4MjI3NTEsImV4cCI6MjEwMjM5ODc1MX0.zQBAZuq1Zk2eEWTaoT9hQtoe84UnN-m7uN6Y5FPQqmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function armazenamentoPersistente() {
  try {
    return typeof window !== "undefined" ? window.localStorage : undefined;
  } catch {
    return undefined;
  }
}
const sessao = sessaoDaAba(
  typeof window !== "undefined" ? sessionStorage : undefined,
  "sb-vsnvzgcotnrxrbztrxlp-auth-token",
  typeof window !== "undefined" ? crypto.randomUUID() : "server",
  armazenamentoPersistente(),
);
export const lembrarNesteDispositivo = (enabled: boolean) => sessao.lembrar?.(enabled) ?? false;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Cada janela/aba mantém sua própria sessão. Isso evita que criar ou entrar
    // com outra conta em uma segunda janela troque silenciosamente a conta em uso.
    // A sessão ainda sobrevive a recarregamentos da mesma aba.
    storageKey: sessao.storageKey,
    storage: sessao.storage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
